repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: d2425a62376c2197448cce2f825d5a0c3926b862
    hooks:
      - id: pretty-format-java
        args: [ --autofix ]
