package com.enums;

public enum ConfigPropertiesEnum {
  URL,
  BROWSER,
  OVERRIDEREPORTS,
  PASSEDSTEPSSCREENSHOTS,
  FAILEDSTEPSSCREENSHOTS,
  SKIPPEDSTEPSSCREENSHOTS,
  RETRYFAILEDTESTS,
  RUNMODE,
  SENDRESULTTOELK,
  SELENIUMGRIDURL,
  ELASTICSEARCHURL;
}
