# This is a sample workflow to trigger GitHub actions workflow
name: nightly-trigger-workflow

on:
  push:
    branches:
      - main
      - 'releases/**'
    branches-ignore:
      - develop

  pull-request:
    types: [ opened, synchronize, ]


