# This is a sample workflow to trigger GitHub actions workflow
name: nightly-trigger-workflow

on:
  push:
    branches:
      - main
      - 'releases/**'
    branches-ignore:
      - develop

  pull-request:
    types: [ opened, synchronize ]

  issues:
    types:
      - opened
      - labeled

  # Workflow can be triggered both manually
  workflow_dispatch:

on:
  schedule:
    - cron: '0 22 * * *'

