name: Java Code Format

on:
#  push:
#    branches: [ main ]

  pull_request:
    branches:
      - "main"

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          skip-commit: true

      - name: git push
        run: |
          git commit --all -m "Google Java Format"
          git push origin HEAD:${{ github.ref_name }}