name: Run Playwright tests using GitHub actions

on: # 1. Choose the trigger
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  Run-Playwright-web-tests:
    runs-on: ubuntu-latest # 2. Choose the runner

    steps:
      - name: Checkout repository into the runner
        uses: actions/checkout@v3 # 3. Checkout git repo

      - name: Set up Java
        uses: actions/setup-java@v3 # 4. Set up Java in runner
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Selenoid Container
        uses: n-ton4/selenoid-github-action@master # 5. Set up and start Selenoid inside container
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1

      - name: Run tests
        run:
          ./gradlew clean test --info # 6. Run tests

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ExtentReport-output